config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
  get 'home/about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>"}
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  devise_parameter_sanitizer.permit(:account_update, keys: [:name])
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
   respond_to :HTML
   
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.' 
      else
     render action 'new' 
      end
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def correct_user
 @pin = current_user.pins.find_by(id: params[:id])
 redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
end
 
  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
 <div class="container">
 <!-- Brand and toggle get grouped for better mobile display -->
 <div class="navbar-header">
 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" datatarget="#bs-example-navbar-collapse-1">
 <span class="sr-only">Toggle navigation</span>
 <span class="icon-bar"></span>
 <span class="icon-bar"></span>
 <span class="icon-bar"></span>
 </button>
 <%= link_to 'Fake Ass Pinterest', root_path, class: 'navbar-brand' %>
 </div>
 <!-- Collect the nav links, forms, and other content for toggling -->
 
 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
   <ul class="nav navbar-nav navbar-right">
   <li><%= link_to 'Home', root_path %></li>
   <li><%= link_to 'About Me', home_about_path %></li>
   <li><%=link_to 'List Pins', pins_path %></li>
 <% if user_signed_in? %>
   <li><%= link_to 'Login', new_user_session_path %></li>
   <li><%= link_to 'Add Pin', new_pin_path %></li>
   <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
   <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
 <% else %>
   <li><%= link_to 'Login', new_user_session_path %></li>
   <li><%= link_to "Join", new_user_registration_path %></li>
 <% end %>
 </ul>
 </div><!-- /.navbar-collapse -->
 </div><!-- /.container -->
 </nav>

app/views/home/_jumbo.html.erb
<div class="jumbotron center">
    <h1>Welcome to my App</h1>
    <p>I'm tired of this shit</p>
    
    <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-default' %>
        <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-default' %>
        <%= link_to 'List Pins', pins_path, class: 'btn btn-default' %>
    <% else %>
        <%= link_to "Login", new_user_session_path, class: 'btn btn-default' %>
        <%= link_to "Join", new_user_registration_path, class: 'btn btn-default' %>
    <% end %>

</div>

app/views/home/about.html.erb
<h1>About Marcelous</h1>
<p>This is my 3rd attempt and I'm just about sick of this shit haha</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Marcelous' page</title>
    <%= stylesheet_link_tag      'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width-device-width, initial-scale-1, maximum-scale-1">
</head>
<body>
<%= render 'home/header' %>

<div class="container">
<% flash.each do |name, msg| %>
 <%= content_tag( :div, msg, class: "alert alert-info") %>
<% end %>

<%= yield %>
</div>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
<div class='form-group'>
   <%= f.label :image %>
   <%= f.file_field :image, class: "form-control" %>
</div> 
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
<div class="panel panel-heading><h1>Editing Pin</h1></div>
<div class="panel-body">
<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

<div class="panel-footer">
</div>
</div>

app/views/pins/index.html.erb
<%= render 'home/jumbo' unless user_signed_in? %>

<div id= "pins" class='transitions-enabled'>
    <% @pins.each do |pin| %>
    
    <div class= "box">
    <%= link_to image_tag(pin.image.url), pin %>
    <div class="panel-body"></div>
    <%= pin.description %></br>
    <%= pin.user.name if pin.user %>
    
    <% if pin.user == current_user %></br>
     <%= link_to 'Edit', (pin) %>
     <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></br>
    <% end %>
    </br>
    </div>
    <% end %>
    
</div>

</div>
<div class = "center">
<%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
        <div class="panel panel-heading"<h2>New Pin</h2></div>
    <div class="panel-body">
        <%= render 'form' %>
        <div class="panel-footer"><%= link_to 'Back', pins_path %></div>
    </div>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class=" col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <div class="panel-body">
        <p>
          <%= image_tag (@pin.image.url (:medium)) %></br>
          <%= @pin.description %>
        </p>
         <%= @pin.user.name %></br>
        <%= link_to 'Edit', edit_pin_path(@pin) %> |
        <%= link_to 'Back', pins_path %>
        </div>
      </div>
    </div>
  </div>
</div>